package com.soen6441.core.tower;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;
import org.dom4j.tree.DefaultElement;

import com.soen6441.core.IArchive;


/**
 * This class responds to manage towers. Such as, create, upgrade, etc. 
 * This class uses dom4j to read XML files.
 * 
 * @see TowerManagerFactory
 * @see Tower
 * 
 * @author Haiyang Sun
 *
 * @version $Revision: 1.0 $
 */

public class TowerManager implements IArchive {
	
	/*
	 * Properties of TowerManager
	 */
	private String towerType;
	private String filePath;
	private int initialPrice;
	
	/*
	 * This list is used to store all levels of tower object of a particular tower type.
	 */
	private List<Tower> leveledTowers = new ArrayList<Tower>();
	
	/**
	 * Constructor of TowerManager.
	 * Call analyze method to generate all levels of a particular type of tower.
	 * 
	 * @param towerType The string use to defines a special type of tower.
	 * @param filePath The string use to define a file path of TowerManager.
	 * @see #analyse() 
     */
	public TowerManager(String towerType, String filePath) {
		
		this.towerType = towerType;
		this.filePath = filePath;
		this.analyse();
	}
	
	/**
	 * This method is used to read and analyze files that store tower information.
	 * Get an XML element to decode.
	 */
	public void analyse() {
		
		//Read XML file which stores tower information.
		SAXReader reader = new SAXReader();
	    Document document = null;
	    
		try {
			document = reader.read(filePath);
		} catch (DocumentException e) {
			e.printStackTrace();
		}
		
		Element root = document.getRootElement();
		
		this.decode(root);
		
	}
	
	public class NameForArchiving{
		
		public static final String Class = "TowerManager";
		private static final String InitialPrice = "initialPrice";
		private static final String LeveledTowers = "leveledTowers";
	
	}
	
	
	/**
	 * This method uses reflection to generate a particular type of tower object.
	 * 
	 * @param typeName The string use to defines a special type of tower.
	 * @return tower A child class of Tower object. 
     */
	private Tower generateTower(String typeName) {
		Tower tower = null;
		try {
			tower = (Tower) (Class.forName("com.soen6441.core.tower." + typeName).newInstance());
		} catch (InstantiationException | IllegalAccessException
				| ClassNotFoundException e) {
			e.printStackTrace();
		} 
		return tower;
	}
	
	
	/**
	 * All levels of tower object will be generated by this method and will be put in leveledTower list.
	 * @see IArchive
	 */
	@Override
	public void decode(Element root) {
		
		Element towerManagerElement = root.element(NameForArchiving.Class);
        this.initialPrice = (Integer.parseInt(towerManagerElement.element(NameForArchiving.InitialPrice).getText()));
        Element leveledTowersElement = towerManagerElement.element(NameForArchiving.LeveledTowers);
        
        //Generate tower depending on towerType property of this class.
        for ( @SuppressWarnings("rawtypes")Iterator i = leveledTowersElement.elementIterator(); i.hasNext(); ) {
        	
            Element element = (Element)i.next();
                        
            Tower tower = this.generateTower(towerType);
            
            tower.setManager(this);
    		
    		tower.decode(element);
    		
    		leveledTowers.add(tower);
           	
        }
		
	}

	@Override
	public Element encode() {
		
		Element element = new DefaultElement(NameForArchiving.Class);
		element.addElement(NameForArchiving.InitialPrice).addText(String.valueOf(this.getInitialPrice()));
		return element;
	}	
	
	/**
	 * Create a specific Tower object.
	 * This method uses copyTo method of tower class.
	 * 
	 * @return Tower 
     * @see Tower#copyTo(Tower) 
     */
	public Tower createTower() {
		
		Tower tower = leveledTowers.get(0);
		Tower newTower = this.generateTower(towerType);
		tower.copyTo(newTower);
		return newTower;
		
	}
	
	/**
	 * This method is used to upgrade an existing tower.
	 * This method uses copyTo method of tower class.
	 * 
	 * @param tower a Tower object
	 * @see Tower#copyTo(Tower) 
     */
	public void upgrade(Tower tower) {
		
		if (tower.level < leveledTowers.size()) {
			leveledTowers.get(tower.level).copyTo(tower);
		}
		
	}
	
	/**
	 * Check whether the tower is in its highest level, if it is, return false, else return true;
	 * To use this method should call from tower
	 * 
	 * @param tower an existing tower
	 * @return boolean 
     * @see Tower#canUpgrade() 
     */
	public boolean canUpgrade(Tower tower) {
		
		if (tower.level >= leveledTowers.size()) {
			return false;
		}
		return true;
	}

	/**
	 * Method getTowerType.
	 * @return String 
	 */
	public String getTowerType() {
		return towerType;
	}

	/**
	 * Method setTowerType.
	 * @param towerType String
	 */
	public void setTowerType(String towerType) {
		this.towerType = towerType;
	}

	/**
	 * Method getFilePath.
	 * @return String 
     */
	public String getFilePath() {
		return filePath;
	}

	/**
	 * Method setFilePath.
	 * @param filePath String
	 */
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	/**
	 * Method getInitialPrice.
	 * @return int 
     */
	public int getInitialPrice() {
		return initialPrice;
	}

	/**
	 * Method setInitialPrice.
	 * @param initialPrice int
	 */
	public void setInitialPrice(int initialPrice) {
		this.initialPrice = initialPrice;
	}

	/**
	 * Method getLeveledTowers.
	 * @return List<Tower> 
	 */
	public List<Tower> getLeveledTowers() {
		return leveledTowers;
	}

	/**
	 * Method setLeveledTowers.
	 * @param leveledTowers List<Tower>
	 */
	public void setLeveledTowers(List<Tower> leveledTowers) {
		this.leveledTowers = leveledTowers;
	}


	
}
